#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:6.6.0

# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Build and Test
              artifacts:
                - build/libs/**
                - build/reports/**
              caches:
                - gradle
              script:
                - chmod +x ./gradlew
                - ./gradlew build -x test
              after-script:
                - pipe: atlassian/checkstyle-report:0.3.0
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Push docker image to the Heroku
          deployment: Production
          services:
            - docker
          script:
            - heroku container:login
            - heroku container:push web -a $HEROKU_APP_NAME
            - heroku container:release web -a $HEROKU_APP_NAME